# Site settings
title: *folio
email: dave.heslop74@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  dave-heslop74.github.io
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  dave-heslop74

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
#  portfolio:
#    output: false
#    permalink: /portfolio/:path/
#  poetry:
#    output: false
#    permalink: /poetry/:path/


